### ISSUE TITLE
Invalid NODE_MODULE_VERSION for electron 4.0 pre-gyp file

### ISSUE THREAD

**Issue by adipascu** [TryGhost/node-sqlite3#1133]
I have this error:
```
Uncaught Error: The module '/node_modules/sqlite3/lib/binding/electron-v4.0-darwin-x64/node_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69.
```

I am using `electron 4.0.8` , it expects `ABI 69`, node-pre-gyp downloads [this file](https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/electron-v4.0-darwin-x64.tar.gz), the cached build has `ABI 64` instead.

It looks like there is an issue with electron not respecting semver, see electron/electron#17324 .

Current workarounds:
 - rebuilding the modules from source (`build_from_source`)
 - ~downgrading to `electron 4.0.3`~ this is a bad idea, looks like electron 4.0.0 to 4.0.3 has an incorrect ABI version, this can cause undefined behavior at runtime

**Comment by paulbennet** [comment]
Same issue with our app too. Would be great if a new binary is pushed soon.

**Comment by pbmzero** [comment]
What's frustrating about this problem is that it _is_ possible to compile 10.11.0 and electron@4.1.1 on a Windows 10 64-bit machine. After about a week of trying on different systems i did manage to get one system building and packaging sqlite3.   The problem is it's not repeatable at all, for the life of me i can't get it running on my main build system. 

If the node, windows-build-tools, electron, OS+bit level, gyp, dependencies are all at the same version level how can i have two different outcomes?  Is there some commands i can run to compare the system that doesn't work with the one that does?

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3 please? 🙂
