### ISSUE TITLE
Can cached database connections be aware of file changes?

### ISSUE THREAD

**Issue by JamesChevalier** [TryGhost/node-sqlite3#1277]
The code that makes `sqlite3.cached.Database()` possible doesn't seem to refresh the cache when the file has changed.

https://github.com/mapbox/node-sqlite3/blob/2bd051da1c9a510544eb6c932c1fd287ad16889b/lib/sqlite3.js#L30-L57

Would that be something that could/should be added here? I'm well out of my depth on this, but something probably a bit less horrible than this:

```js
var fs = require('fs');
var currentTimestamp = fs.statSync(file).mtime.valueOf();
if (!sqlite3.cached.objects[file]) {
  db = sqlite3.cached.objects[file] = new Database(file, a, b);
  sqlite3.cached.objects[file + 'timestamp'] = currentTimestamp;
}
else {
  if(currentTimestamp === sqlite3.cached.objects[file + 'timestamp']) {
    db = sqlite3.cached.objects[file];
  } else {
    db = sqlite3.cached.objects[file] = new Database(file, a, b);
    sqlite3.cached.objects[file + 'timestamp'] = currentTimestamp;
  }

  // Make sure the callback is called.
  var callback = (typeof a === 'number') ? b : a;
  if (typeof callback === 'function') {
      if (db.open) process.nextTick(cb);
      else db.once('open', cb);
  }
}
```

Or is this something that's out of scope and should be handled externally (in my app)? If that's the case, do I reset the cache with `sqlite3.cached.objects[file] = null;` prior to calling `sqlite3.cached.Database()`?

**Comment by bedwardly-down** [comment]
Would [this](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/synchronizer.js) from another project I'm contributing to be helpful to you here? From what I could tell, they had to upgrade the Database manually each time changes were made. And [here's](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/joplin-database.js) the actual database specific implementations.

**Comment by JamesChevalier** [comment]
That seems like a good approach, but I don't think it would work for my specific use case.

It looks like they're [storing the current version in the database itself](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/joplin-database.js#L722). Then they're [storing a list of possible versions in the code](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/joplin-database.js#L311). The upgradeDatabase code does any required updates, returns whatever the new version of the database is, and [if the existing version doesn't match the updated version they refresh the tables](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/joplin-database.js#L737).

In my specific use case, the code doesn't know anything about database versioning. I have a separate process that builds sqlite databases, and copies them into place for my customized mbtiles server (based on [tobinbradley/mbtiles-server](https://github.com/tobinbradley/mbtiles-server)).

**Comment by bedwardly-down** [comment]
Thanks for getting back to me. I'm not a programmer and just started helping out here, so I'm not completely sure how this works myself. I just knew from my brief dabbling and a botched attempt at fixing a bug where the database info was. Ha

From what I can tell, this repo is not massively active except for code specific fixes and various upgrades that are being needed to keep node-sqlite3 functioning and usable, so depending on how soon you need this info by, you may have to wing it a bit with what you've already started. If it works, I say use it if it doesn't destroy anything in the process until someone much smarter than I can step in. :D

**Comment by aikar** [comment]
In what way do you mean file changes? deleting file and making a new one? external updates?

cache doesn't load entire file into memory (least that im aware of) it just makes sure that if 3 files call new Database(file) on same file, it's same shared handle, sharing some locks, etc.

Otherwise, 3 new instances each open their own handles.

in both cases, an external (out of instance update) should still be seen.

There isn't anything to be done here.

**Comment by JamesChevalier** [comment]
> In what way do you mean file changes? deleting file and making a new one? external updates?

I'm periodically replacing the mbtiles files with new versions, so I think 'deleting file and making a new one' is likely the most accurate description.

> cache doesn't load entire file into memory (least that im aware of) it just makes sure that if 3 files call new Database(file) on same file, it's same shared handle, sharing some locks, etc.
> Otherwise, 3 new instances each open their own handles.
> in both cases, an external (out of instance update) should still be seen.

Apologies, I don't understand this description (specifically around the note of '3 files call new Database(file)'). I've been reading [this section of code](https://github.com/mapbox/node-sqlite3/blob/2bd051da1c9a510544eb6c932c1fd287ad16889b/lib/sqlite3.js#L30-L57) as it storing the database in memory. Specifically [this line](https://github.com/mapbox/node-sqlite3/blob/2bd051da1c9a510544eb6c932c1fd287ad16889b/lib/sqlite3.js#L46) looks like it's not re-opening the database.

Thanks for trying to help me understand this. 😄

**Comment by aikar** [comment]
You are correct in that it doesn't re-open the file. However the contents do not get loaded into memory. SQLite operates on reading the data from disk.

Some people operate on 60GB DB's, don't want to load that into memory :)

But for your case, is it really necessary to delete them? Could you not manipulate them externally instead keeping same file?

But if not, then sounds like you shouldn't be using the cached version anyways, just use the new sqlite3.Database() option and maintain a reference to the DB.
You could use solutions for nodejs that monitor a file for changes, and then do something like (this is psuedo code, the watcher code will depend on the library you use):

```javascript
export let db: Database = new sqlite3.Database("file.db");
watcher.onChange("file.db", (file, changeType) => {
if (changeType == "delete" || changeType == "create" ) { // don't do it on file content changes
    db.close();
    db = new Database("file.db");
}
});
```
then in other files using the db just do import {db} from "./db";

**Comment by bedwardly-down** [comment]
So basically migrate changes between two or more different databases the way that game patchers update game databases or compressed files? That makes sense to me

**Comment by aikar** [comment]
It really depends what data is changing and how.

Are you downloading DB's from somewhere else that you have no idea what changed?

Then yes swapping the db's out makes sense.

But might be better to simply stop your process, change file out, start it back up rather than dealing with hot reloading in a live app.

If you are the one creating the new db, and you could change the process to mutate existing data rather than build new, then you can do that and modify the file in place while the app is running, just make sure your changes are done in transactions where appropriate.

But ultimately it boils down to, does your app really need to stay running during this?

could also do something like file.db, write new file to file.next.db
then in your app instead of doing a file watcher like I suggested earlier, do

const db: Promise<Database> = Promise.resolve(new Database("file.db"));

process.on('SIGUSR2', async () => {
const prevdb = await db;
db = new Promise(resolve => { 
await prevdb.close();
await fs.unlink("file.db");
await fs.rename("file.next.db", "file.db");
resolve(new Database("file.db"));
});
});

export async function getDB() {
    return db;
}

then anytime you need to replace file, put new one in file.next.db, then send SIGUSR2 to the current process to trigger a hot reload.
 
But again, question if you really need hot reloading.

**Comment by bedwardly-down** [comment]
Thanks for answering. I’m not using any of this directly but am still wanting to learn what i can in order to at least be somewhat useful. 😸
