### ISSUE TITLE
Access Denied: Linux precompiled binaries

### ISSUE THREAD

**Issue by andrew-barnett** [TryGhost/node-sqlite3#1389]
The URL https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz is returning an Access Denied error. (The v3 URL, https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v3-linux-x64.tar.gz, is fine.)

```sh
$ git clone https://github.com/mapbox/node-sqlite3.git
...
$ cd node-sqlite3/
$ npm install node-pre-gyp
...
$ ./node_modules/.bin/node-pre-gyp reveal
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@12.18.4 | linux | x64
{
  "name": "sqlite3",
  "configuration": "Release",
  "module_name": "node_sqlite3",
  "version": "5.0.1",
  "prerelease": "",
  "build": "",
  "major": 5,
  "minor": 0,
  "patch": 1,
  "runtime": "node",
  "node_abi": "node-v72",
  "node_abi_napi": "napi",
  "napi_version": "6",
  "napi_build_version": 3,
  "node_napi_label": "napi-v3",
  "target": "",
  "platform": "linux",
  "target_platform": "linux",
  "arch": "x64",
  "target_arch": "x64",
  "libc": "glibc",
  "module_main": "./lib/sqlite3",
  "toolset": "",
  "host": "https://mapbox-node-binary.s3.amazonaws.com/",
  "module_path": "/usr/app/node-sqlite3/lib/binding/napi-v3-linux-x64",
  "module": "/usr/app/node-sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node",
  "remote_path": "./sqlite3/v5.0.1/",
  "package_name": "napi-v3-linux-x64.tar.gz",
  "staged_tarball": "build/stage/sqlite3/v5.0.1/napi-v3-linux-x64.tar.gz",
  "hosted_path": "https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/",
  "hosted_tarball": "https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v3-linux-x64.tar.gz"
}
{
  "name": "sqlite3",
  "configuration": "Release",
  "module_name": "node_sqlite3",
  "version": "5.0.1",
  "prerelease": "",
  "build": "",
  "major": 5,
  "minor": 0,
  "patch": 1,
  "runtime": "node",
  "node_abi": "node-v72",
  "node_abi_napi": "napi",
  "napi_version": "6",
  "napi_build_version": 6,
  "node_napi_label": "napi-v6",
  "target": "",
  "platform": "linux",
  "target_platform": "linux",
  "arch": "x64",
  "target_arch": "x64",
  "libc": "glibc",
  "module_main": "./lib/sqlite3",
  "toolset": "",
  "host": "https://mapbox-node-binary.s3.amazonaws.com/",
  "module_path": "/usr/app/node-sqlite3/lib/binding/napi-v6-linux-x64",
  "module": "/usr/app/node-sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node",
  "remote_path": "./sqlite3/v5.0.1/",
  "package_name": "napi-v6-linux-x64.tar.gz",
  "staged_tarball": "build/stage/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz",
  "hosted_path": "https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/",
  "hosted_tarball": "https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz"
}
node-pre-gyp info ok 
$ ./node_modules/.bin/node-pre-gyp reveal hosted_tarball --silent
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v3-linux-x64.tar.gz
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
$ curl -s -L -o napi-v6-linux-x64.tar.gz https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
$ cat napi-v6-linux-x64.tar.gz 
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>9A62407AA8EC561B</RequestId><HostId>XO6dyy/dS5Xks3WA3/cLZZDnJXRhUwkTeW0sqsyTVGuVAAty0fpJbF8M8U8G3UZAHn4lKmmMN1g=</HostId></Error>
```

**Comment by KatSick** [comment]
same for me here

**Comment by benhovinga** [comment]
I am trying to get [Strapi](/strapi/strapi) up and running with `npx create-strapi-app fueld-api --quickstart` and I get [this error(gist)](https://gist.github.com/benhovinga/99c4a6d8778301d3380f16524e110e5c).

Looking into the log I notice an HTTP 403 - Forbidden return on a download for `https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz`
```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@12.18.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
```
No idea if this is an issue with strapi, sqlite3, or gyp. However, because I see the failed download is a sqlite3 package I figured I would report the issue to this repo first.

**My Environment**:
- Windows 10 (10.0.19041.685)
  - WSL 1
    - Ubuntu-18.04
      - NPM 6.14.4
      - Node 12.18.0

**Comment by Niggl1999** [comment]
Same over here installing sqlite3.
Package managers: npm, yarn and pnpm
Build envs:
* Win 10 - NodeJS 14 and 15
* Docker: node:alpine, node:latest and node:14.15.1-alpine3.12

Same 403 on the mapbox link while installing.

Only the relevant part:
```
node-pre-gyp info it worked if it ends with ok
--
34 | node-pre-gyp info using node-pre-gyp@0.11.0
35 | node-pre-gyp info using node@14.15.1 \| linux \| x64
36 | node-pre-gyp WARN Using request for node-pre-gyp https download
37 | node-pre-gyp info check checked for "/drone/src/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node" (not found)
38 | node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
39 | node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
40 | node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
41 | node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@14.15.1 (node-v83 ABI, musl) (falling back to source compile with node-gyp)
42 | node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
```

**Comment by Niggl1999** [comment]
Little update:
Pinning sqlite3 to 5.0.0 in my package.json at least let's me work with that version of sqlite3 and doesn't break build any more.
Would still be nice to get this resolved :)

```
{
  "dependencies": {
    "sqlite3": "5.0.0"
  }
}
```

**Comment by elsiehupp** [comment]
I'm getting the same problem on Ubuntu x64 for `sqlite3` v4.1.0:

https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v83-linux-x64.tar.gz

Mentioned in: https://github.com/laurent22/joplin/issues/4385

**Comment by ValeTheVioletMote** [comment]
Same problem here, both on Windows and Linux. Couldn't install 4.20. Then tried doing latest, also failed. Specifying to install @5.0.0 worked though.

**Comment by elsiehupp** [comment]
FWIW the error ultimately went away for me when I resolved `npm install` not working correctly (by wiping my cloned repository and doing a hard reset), so my guess here is that in at least some cases the real problem is `node-pre-gyp` generating an invalid URL, not a valid download being missing from the server.

**Comment by ozdeadmeat** [comment]
The downloads are giving an access denied error, until Mapbox fix this problem every install will need to be compiled, which is bloody annoying.

**Comment by MikeDimmickMnetics** [comment]
I _think_ the Access Denied errors are really Not Found. Apparently AWS S3 will report 403 Access Denied if the (anonymous) user doesn't have ListBucket permission: https://jamesthom.as/2021/02/aws-s3-iam-errors-with-missing-files-404-expected-403-returned/

The files for Node-API v6 were not uploaded by the build for 5.0.1 - see #1444 and commit 60a022c, and also https://github.com/mapbox/node-sqlite3/issues/1424#issuecomment-779125553. For now use version 5.0.2 or 5.0.0, which only support Node-API v3. According to the [support matrix](https://nodejs.org/api/n-api.html#n_api_node_api_version_matrix) Node-API v3 is supported for all versions after Node 6.14.2. A later version of Node.js could drop support for older versions of Node-API, but at the time I wrote this, Node 16.x still supported Node-API v3.

If you really need version 5.0.1, you will need to have the build tools installed and configured for your platform, so that `node-gyp` can build the binaries from source.

**Comment by ozdeadmeat** [comment]
Or, you know, put the pre-compiled version somewhere people could get a hold of it. Downloading 4GB of compilers to compile this is just piss poor infrastructure management, not everyone wants to fuck around with compilers. Some of us just want easier access to the node.

**Comment by daniellockyer** [comment]
Please try with v5.0.3 🙂
