### ISSUE TITLE
[Debugging] Differences between Trace and Profile

### ISSUE THREAD

**Issue by vsviridov** [TryGhost/node-sqlite3#1474]
Hello, currently i'm using version `5.0.2`

When I'm using the `profile` and `trace` events, I get different output.

With `trace` event, the resulting query has all the placeholders resolved, e.g. `SELECT * FROM foo WHERE bar = 123`.
With `profile` event, the placeholders are not resolved, e.g. `SELECT * FROM foo WHERE bar = ?`.

I wonder if it's intentional. Also, if there's a way to get a version with placeholders, is it possible to receive parameters to the query as well?

**Comment by xdandyx** [comment]
And , when i listen events  `both profile and trace `,only the last works ! so strange!

**Comment by daniellockyer** [comment]
The differences are explained here: https://www.sqlite.org/c3ref/profile.html 🙂

**Comment by vsviridov** [comment]
Do you plan to support the `trace_v2` call?

**Comment by dkamins** [comment]
Re currently used trace and profile approach: "These routines are deprecated. Use the [sqlite3_trace_v2()](https://www.sqlite.org/c3ref/trace_v2.html) interface instead of the routines described here."
-- https://www.sqlite.org/c3ref/profile.html

And the new v2 version: "Each call to either sqlite3_trace(D,X,P) or sqlite3_trace_v2(D,M,X,P) overrides (cancels) all prior calls to sqlite3_trace(D,X,P) or sqlite3_trace_v2(D,M,X,P) for the database connection D. Each database connection may have at most one trace callback."
-- https://www.sqlite.org/c3ref/trace_v2.html

The v2 conceptual model differs slightly in that now a single callback is registered with a [trace bitmask](https://www.sqlite.org/c3ref/c_trace.html) comprised of:
```
#define SQLITE_TRACE_STMT       0x01
#define SQLITE_TRACE_PROFILE    0x02
#define SQLITE_TRACE_ROW        0x04
#define SQLITE_TRACE_CLOSE      0x08
```

Presumably the underlying library is now pushing the currently used deprecated (apparently since 2016) versions through the v2 path, which means only the last one applies. This matches what I'm seeing and what @xdewx mentioned: only the last registered trace or profile currently triggers now.

For reference, cpython made the change to v2 for themselves in 2020 here:
https://github.com/python/cpython/issues/84498

It's probably a good idea and time for this library to adapt to the v2 approach!
