### ISSUE TITLE
Module doesn't work on Windows with io.js v2.0.x

### ISSUE THREAD

**Issue by v12** [TryGhost/node-sqlite3#449]
Hello there,

I'm experiencing an issue with sqlite3 module usage on Windows 8.1 x64 machine, though everything is absolutely fine with similar setup on Linux.

`npm i sqlite3` output - [gist](https://gist.github.com/v12/07213de62343ba10f133)

As you can see, installation via npm went fine, however, when I try to use the module in the code, I get the following error:

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Dev\projects\sqlite3-test\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

**io.js** versions tested: **v2.0.0** and **v2.0.1**
**sqlite3** version is **v3.0.8**

Let me know if you require any additional information.

**Comment by nik045** [comment]
u r right :+1:

**Comment by magicdawn** [comment]
same on iojs@1.6.3

**Comment by springmeyer** [comment]
Thanks for the report. Just seeing this now. Two problems:

1) Ideally a source compile should not be needed. Turns out I made a mistake in packaging and the binary is missing. Going to work on that in #469
2) ^^ the binary might be missing because of the problem you are hitting `Module did not self-register`. Will need some time to recall what might cause this.

https://github.com/nodejs/io.js/issues/751 looks like it was a mis-configuration and is not a bug/the cause of this conclusively. However https://github.com/nodejs/io.js/issues/751 might be involved.

**Comment by springmeyer** [comment]
Anyone hitting this should be able to workaround it by using node `v0.10.x` or `v0.12.x`.

**Comment by novacrazy** [comment]
Downgrading is not an option for me, what else can you suggest for using this library?

**Comment by daniellockyer** [comment]
Please try with the latest version - v5.0.3 🙂
