### ISSUE TITLE
node-pre-gyp dependency should not be kept in memory during runtime

### ISSUE THREAD

**Issue by rikelme** [TryGhost/node-sqlite3#681]
Why is this the case? sqlite3 is the only native module (I've used so far) to keeps the node-pre-gyp dependency throughout its life cycle.

**Comment by rikelme** [comment]
Can this be done without requiring node-pre-gyp?

```
var binary = require('node-pre-gyp');
var path = require('path');
var binding_path = binary.find(path.resolve(path.join(__dirname,'../package.json')));
var binding = require(binding_path);
var sqlite3 = module.exports = exports = binding;
var EventEmitter = require('events').EventEmitter;
```

**Comment by Mithgol** [comment]
Many of [node-pre-gyp's dependents](https://www.npmjs.com/browse/depended/node-pre-gyp) do the same. Some of the other, such as [`serialport`](https://www.npmjs.com/package/serialport) for example, use [`bindings`](https://www.npmjs.com/package/bindings) to locate the addon. I'm not sure if they're winning anything memory-wise.

On the other hand, a mere `delete binary` or `binary = null` won't bring `node-preg-gyp` out of memory because Node.js has its [module caching](https://nodejs.org/docs/latest/api/modules.html#modules_caching).
