### ISSUE TITLE
Latest Version of nwjs supported 

### ISSUE THREAD

**Issue by jpcharlesworth** [TryGhost/node-sqlite3#727]
I recently successfully built node-sqlite3 for nwjs version 0.14.7 LTS but failed with the then latest version 0.17.6. Is there a way to find out the latest version of nwjs supported without having to go through the complex process of trying to build for it?

**Comment by Mithgol** [comment]
It's possible to start providing custom NW.js builds of node-sqlite3 if the result of #252 is reassembled (from its current [remnants](https://github.com/mapbox/node-sqlite3/blob/4800c6377ef15f467290d77776302b486e71ada3/.travis.yml#L135-L136)) over the limitations introduced on Travis CI by the [migration from their old infrastructure to their new container-based infrastructure](https://docs.travis-ci.com/user/migrating-from-legacy/).

That migration allowed builds to start much faster and also to run faster (that's why node-sqlite3 opted in), but the newer infrastructure does not allow `sudo`. It brings the following problems:

* **Installing the missing dependencies (about 20 APT packages) necessary for NW.js to run in Linux 32-bit mode.** Currently we are rootless and therefore [installing packages on the container-based infrastructure](https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Container-Based-Infrastructure) adheres to a [whitelist](https://github.com/travis-ci/apt-source-whitelist). I haven't yet checked whether those 20 are all whitelisted.

* **Running a headless NW.js to perform tests.** The code of #252 used [X Virtual Framebuffer](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI) for that. I haven't yet checked if the new infrastructure supports it. Might wait for the decision at https://github.com/nwjs/nw.js/issues/769#issuecomment-259867271 and see if it's positive.

* **Performing 32-bit builds of node-sqlite3** (both for NW.js and for Node.js, which is currently disabled [as well](https://github.com/mapbox/node-sqlite3/blob/4800c6377ef15f467290d77776302b486e71ada3/scripts/build_against_node.sh#L42-L79)). Not sure if doable. If it's a dead end, then we might as well build in a Docker container running a 32-bit system (as recommended in https://github.com/travis-ci/travis-ci/issues/5770#issuecomment-197771661 once). Which also would mean having `sudo` inside the container (it's nice) but it might require `sudo` outside (as seen in andlabs/libui#157 and in [Travis CI docs](https://docs.travis-ci.com/user/docker/), though the example at https://github.com/travis-ci/travis-ci/issues/5770#issuecomment-197771661 does not imply it) which would kinda defeat the purpose because the container-based infrastructure does not provide `sudo`.

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
