### ISSUE TITLE
Overriding URLs for binary downloads

### ISSUE THREAD

**Issue by mstade** [TryGhost/node-sqlite3#734]
We're trying to install jsbin, which depends on sqlite3@2.2.4. Unfortunately, we're firewalled and must use internal package hosting alternatives. We also can't build from source, because of a lack of tooling on the relevant boxes. What we *can* do is host the binaries internally, but we must have a way then to configure the download URLs. I can't seem to find any documentation related to this -- is it possible?

**Comment by ErisDS** [comment]
Hi @mstade, totally understand your situation however to the best of my knowledge there is no configuration option because these details are provided via the project's package.json.

I believe the correct place to request this feature would be on the [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) repository, which is the module that handles the binaries. 

The best workaround I can think of would be to fork this repository, and set the package.json details in your fork to your own aws mirror.

Alternatively, given your situation, perhaps including your dependencies in your deployment would work?

**Comment by mstade** [comment]
Thanks for the quick response @ErisDS! I just had a look at node-pre-gyp docs, and it looks like maybe this is an option: https://www.npmjs.com/package/node-pre-gyp#download-binary-files-from-a-mirror

The "because China" comment is tragically comical. I'm going to try this and report back any progress, thanks for the pointer!
