### ISSUE TITLE
Update database twice and then insert sequence stepup 

### ISSUE THREAD

**Issue by shilpi-verma-izap** [TryGhost/node-sqlite3#915]

**Comment by wmertens** [comment]
Hi, this is an open source project, and your issue is not very helpful. I use this project too and it's sadly getting stale, with 232 open issues and 22 open PRs.

When you create issues for open source projects, please make sure they are descriptive and include a way to reproduce the issue. Maintainers are not getting paid for this. I propose you improve your issue or else close it.
